// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $campaigns_campaign_uid_tracks_track_uid_ from "./routes/campaigns/[campaign_uid]/tracks/[track_uid].tsx";
import * as $campaigns_uid_ from "./routes/campaigns/[uid].tsx";
import * as $index from "./routes/index.tsx";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/campaigns/[campaign_uid]/tracks/[track_uid].tsx":
      $campaigns_campaign_uid_tracks_track_uid_,
    "./routes/campaigns/[uid].tsx": $campaigns_uid_,
    "./routes/index.tsx": $index,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
